GumTreeDiff/gumtree

core/src/main/java/fr/labri/gumtree/actions/RootAndLeavesClassifier.java
Originally `fSrcMvTrees` was unused, the subsequent code wrote to `fsrcDelTrees` again (to no effect). 
Alternatively, if `fSrcMvTrees` should not be used, let me know and I'll remove the redundant code.
Kind regards,
Vincent
=> Fix possible error in RootAndLeavesClassifier

gen.jdt/pom.xml, gen.jdt/src/main/java/fr/labri/gumtree/gen/jdt/AbstractJdtTreeGenerator.java, gen.jdt/src/test/java/gen/jdt/Java8Test.java
The JdtTreeGenerator can now parse Java 8 source files.
I also updated the POM to pull in the updated JDT dependencies. There is also a test that is a simple Java 8 syntax example. It parses correctly.
=> Java 8 Compliance

client/src/test/java/fr/labri/gumtree/client/JdtTest.java, core/src/main/java/fr/labri/gumtree/matchers/heuristic/gt/SubtreeMatcher.java
When trying to diff with an invalid java file, the Matcher would throw an IndexOutOfBoundsException. This would happen because the invalid java file would be parsed into an empty tree. Trying to match with that empty tree would cause the exception.
I added a few tests to highlight the issue. I also fixed the problem by making sure that the currentIdx field would be -1 if the tree was empty.
This is the same as #3, but from a different branch.
=> Fixed an IndexOutOfBoundsException

README.md
The current link to your webpage in the github read me rendering. I explicitly added the protocol to indicate an absolute rather than relative link.
=> Fix contact me link in readme

client.diff/src/main/java/com/github/gumtreediff/client/diff/AbstractDiffClient.java, client.diff/src/main/java/com/github/gumtreediff/client/diff/web/DiffView.java, client.diff/src/main/java/com/github/gumtreediff/client/diff/web/ScriptView.java, core/src/main/java/com/github/gumtreediff/tree/TreeContext.java
Fix for non-existing type labels in source tree context, which are only present in dst tree context. This fixes the issue mentioned in #48.
This should be better done inside of a matcher (I think), but the matcher only receives a tree and not a tree context. Maybe take a closer look yourself before merging.
=> Import type labels of dst tree ctx into src tree ctx

client.diff/src/main/resources/web/dist/gumtree.css
Bootstrap's tooltip-inner css class limits the tooltip width to 200px. Having this property set to 'none' sets the width automatically and prevents text from being cut.
=> Prevent longer entity tooltips from being cut.

core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/GreedyBottomUpMatcher.java
when optimizing new hard cases in [gumtree-spoon-ast-diff](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/), I realized that the default of min similarity is far too low. A value of 0.5 and 0.6 gives much smaller and cleaner diffs.
WDYT?
(What will CI say? Travis OK, no test breaks.)
=> set min similarity to a better default

core/src/main/java/com/github/gumtreediff/matchers/OptimizedVersions.java, core/src/main/java/com/github/gumtreediff/matchers/heuristic/cd/ChangeDistillerParallelLeavesMatcher.java, core/src/main/java/com/github/gumtreediff/matchers/optimizations/CrossMoveMatcherThetaF.java, core/src/main/java/com/github/gumtreediff/matchers/optimizations/IdenticalSubtreeMatcherThetaA.java, core/src/main/java/com/github/gumtreediff/matchers/optimizations/InnerNodesMatcherThetaD.java, core/src/main/java/com/github/gumtreediff/matchers/optimizations/LcsOptMatcherThetaB.java, core/src/main/java/com/github/gumtreediff/matchers/optimizations/LeafMoveMatcherThetaE.java, core/src/main/java/com/github/gumtreediff/matchers/optimizations/UnmappedLeavesMatcherThetaC.java, core/src/test/java/com/github/gumtreediff/test/TestOptimizedMatchers.java
We developed some general optimizations for tree differencing algorithms that also work with GumTree
(see https://doi.org/10.1145/2970276.2970315 ). Perhaps you want to include them.
Sorry that it took me so long to prepare the pull request.
=> Add tree differencing optimizations.

client/src/main/java/com/github/gumtreediff/client/Run.java
You have homogenized all property names in this [commit](https://github.com/GumTreeDiff/gumtree/commit/50e3987a0d8bf5abb0eb5c373275b14805125bc3). However, you forget to apply the change to the command line properties parsing code, thus all properties setting from command line can not take effect.
=> fix parsing property names from command line

core/src/main/java/com/github/gumtreediff/tree/Tree.java
Hi!
I would like to have own implementation of com.github.gumtreediff.tree.Tree. It was no problem to extend Tree and create it using my own TreeContext. Super!
But it is not possible to deepCopy MyTree, because constructor is private.
Thank you
Pavel
=> Support clone of custom Tree

core/src/main/java/com/github/gumtreediff/actions/ChawatheScriptGenerator.java, core/src/test/java/com/github/gumtreediff/test/TestActionGenerator.java
In trying to use this library, I found that the edit scripts generated did **not** always produce the correct output when actually applied to the original tree. I traced the problem to the alignment logic - the indices being accessed when deciding how to align the trees were not always correct.
This pull request fixes these issues and includes a minimal unit test which fails without the fix.
=> Fix to align children logic

client.diff/build.gradle, client.diff/src/main/java/com/github/gumtreediff/client/diff/webdiff/VanillaDiffHtmlBuilder.java, core/build.gradle, core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/CliqueSubtreeMatcher.java
trove4j's last significant commit is from 2018, the last news on its website is from 2009, and the last release (3.1a1) was done in 2014. This PR replaces that dependency with the more up to date [fastutil](http://fastutil.di.unimi.it/).
=> Replaced dependency on trove4j for equivalent dependency on fastutil

client.diff/src/main/java/com/github/gumtreediff/client/diff/HtmlDiff.java, client.diff/src/main/java/com/github/gumtreediff/client/diff/webdiff/VanillaDiffView.java, client.diff/src/main/java/com/github/gumtreediff/client/diff/webdiff/WebDiff.java
These changes add a command called `htmldiff` which dumps HTML output of vanilla-diff in `stdout`. The dependent CSS and JS are read and then dumped directly into this output. However, two changes must be done before it is ready for merge:
=> feat: add command to dump vanilla diff output

core/src/main/java/com/github/gumtreediff/actions/SimplifiedChawatheScriptGenerator.java
Consider the following tree:
where vertices 1, 3, 4, 5 and 6 are added and vertex 2 is already existing (e. g. it's an existing statement moved into a new `if` or a loop).
When the simplification is processing vertex 3 (`t`), `t`'s parent is 1 and `t`'s descendants are 4, 5 and 6. Insertion of 3 gets removed, but insertion of 1 is not transformed into `InsertTree`, because vertex 2 is not added. So, the addition of vertex 3 is lost.
Example of code that demonstrates the issue:
old:
```c
void foo(int a) {
bar();
}
```
new:
```c
void foo(int a) {
if (a == 42) {
bar();
}
}
```
This pull request fixes the issue, so that an insertion is removed only if the addition of the parent node or one of its ancestors is transformed into `InsertTree`.
The same issue applies to `Delete` actions, if the …
=> Fix bug in edit script simplification

core/src/main/java/com/github/gumtreediff/actions/Diff.java, core/src/main/java/com/github/gumtreediff/gen/TreeGenerators.java, core/src/main/java/com/github/gumtreediff/matchers/Matchers.java, core/src/main/java/com/github/gumtreediff/utils/Registry.java, core/src/test/java/com/github/gumtreediff/test/TestDiff.java
This commit is adding a new compute method to support the diff processing of resources instead of paths.
This functionality is intersting when the files that need to be computed are not in the local file and are downloaded from the Internet using APIs in memory.
=> Diff class support for Resources

gen.jdt/src/main/java/com/github/gumtreediff/gen/jdt/JdtVisitor.java, gen.jdt/src/test/java/com/github/gumtreediff/gen/jdt/TestJdtGenerator.java
This PR aims to fix issue https://github.com/GumTreeDiff/gumtree/issues/323.
TypeArguments of the method invocation are ignored after the introduction of MethodInvocationReceiver in 3.0 gen.jdt. 
Since java only allows to pass the type argument in case of having the receiver, I thought its better to have the reciver as the parent of the type arguments. In other words:
`<String> emptyList()`  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; --> This runs into compilation error  ❌
`Collections.<String> emptyList()`&nbsp; -->   Works fine ✅ 
Also, typeArguments seem to be an empty list (not null) in case of having basic method invocations. So there is no need for additional null check.
I have also added a test to capture the newly added subtree.
=> Fix for type arguments of the generic functions in jdt

.dependabot.yml
This enabled [GitHub's depenadabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates) at this repository. It is for free and I personally like it.
It creates pull requests for version updates. Since there are CI checks in place, one can see if the version update causes a harm or not.
=> Enable depandabot

.github/workflows/build-test-gumtree.yml, gen.treesitter/src/test/java/com/github/gumtreediff/gen/treesitter/TreeSitterTreeGeneratorsTest.java
To enable refinement of the Docker image, this PR adds a build to the pipeline.
I think, it works, but internally, tests are failing. I adapted that test. I allowed two values, because the return values are varying:
```
#13 136.2 TreeSitterTreeGeneratorsTest > testPython() FAILED
#13 136.2     org.opentest4j.AssertionFailedError: expected: <13> but was: <9>
#13 136.2         at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
#13 136.2         at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
#13 136.2         at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
#13 136.2         at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
#13 136.2         at …
```
=> Build docker image on CI

core/src/main/java/com/github/gumtreediff/tree/TypeSet.java, core/src/test/java/com/github/gumtreediff/test/TestTree.java
Hello,
I've identified a bug affecting multithreaded execution.
This PR consists of 3 commits, and I'll break down each commit:
- I have created a repeated test (executes in separate threads) ([commit#1](https://github.com/GumTreeDiff/gumtree/commit/94a55c58b017467ddc1eee64f1ce081216157dff)) which runs GumTree _Classic_ matcher on a file revision, and observed discrepancies in the number of generated mappings. To enable a multithreaded environment, I relied on JUnit 5's CONCURRENT execution, requiring the addition of junit-platform.properties.
*Test result in a multithreaded environment **before** the fix*
- After investigating, I realized the issue lies in the equality check for types `getType() == t.getType()`, which works in a single-threaded environment but fails when multiple GumTree …
=> Fix for multithreaded execution

client.diff/src/main/java/com/github/gumtreediff/client/diff/webdiff/VanillaDiffView.java
This was most direct way to avoid the error below and seems consistent with the vanilla.css readFile instance.
```
./dist/build/install/gumtree/bin/gumtree htmldiff /tmp/lhs.mlir /tmp/rhs.mlir
Error while running client 'htmldiff'.
java.lang.NullPointerException
at java.base/java.io.Reader.<init>(Reader.java:168)
at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:112)
at com.github.gumtreediff.client.diff.webdiff.VanillaDiffView$Header.readFile(VanillaDiffView.java:115)
at com.github.gumtreediff.client.diff.webdiff.VanillaDiffView$Header.build(VanillaDiffView.java:106)
at com.github.gumtreediff.client.diff.webdiff.VanillaDiffView.build(VanillaDiffView.java:42)
at com.github.gumtreediff.client.diff.HtmlDiff.run(HtmlDiff.java:67)
at …
```
=> Fix paths of files to read for webdiff

core/src/main/java/com/github/gumtreediff/tree/Tree.java
=> fix: update deepCopy JavaDoc to specify that metadata is not copied.

gen.jdt/src/main/java/com/github/gumtreediff/gen/jdt/JdtVisitor.java, gen.jdt/src/test/java/com/github/gumtreediff/gen/jdt/TestJdtGenerator.java
This is the fix for https://github.com/GumTreeDiff/gumtree/issues/355
```@author john */ class C {}``` now will be represented as:
```
CompilationUnit [0,30]
TypeDeclaration [0,30]
Javadoc [0,19]
TagElement [4,17]
TAG_NAME: @author [4,11]
TextElement:  john  [11,17]
TYPE_DECLARATION_KIND: class [20,25]
SimpleName: C [26,27]
```
=> feat: optionalTagName for javadocs in jdt

core/src/main/java/com/github/gumtreediff/matchers/optimizations/LeafMoveMatcherThetaE.java
This PR fixes a bug in the `ThetaE` optimization logic where adding a new mapping could leave `srcToDst` and `dstToSrc` inconsistent.
In certain cases, a new mapping is added without first removing existing conflicting entries. This can cause one of the maps to still hold the old mapping, leading to lost mappings in the final result.
Example commit demonstrating the issue:
https://github.com/pouryafard75/TestCases/commit/fb4498be010c788a40c108ce6592b29a205634da
**Before optimization:**
**After optimization:**
**My proposed fix:**
Before adding a new mapping, clear any existing entries in both `srcToDst` and `dstToSrc` that conflict with it. This ensures the maps remain consistent.
=> Fix LeafMoveMatcherThetaE
